name: Semgrep Scan

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run Semgrep Scan
        id: semgrep_scan
        run: |
          pip install semgrep
          semgrep scan --config auto > semgrep_results.txt || true
          cat semgrep_results.txt

      - name: Send Notification to Slack
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          CLEAN_SUMMARY=$(tail -n 12 semgrep_results.txt | grep -E "Findings|Targets|Lines|skipped" || echo "Scan completed successfully.")
          ESCAPED_SUMMARY=$(echo "$CLEAN_SUMMARY" | jq -aR . | jq -s -c 'join("\\n")' | sed 's/^"//;s/"$//')
          payload="{\"text\": \"*📊 Semgrep Security Scan Summary (GitHub Actions)*\\n\`\`\`\\n${ESCAPED_SUMMARY}\\n\`\`\`\"}"
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK"
